<Project>
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <Deterministic>true</Deterministic>
    <PackageLicenseExpression>GPL-3.0-only</PackageLicenseExpression>
    <Version>3.0.0</Version>
  </PropertyGroup>
</Project>
